const {get,all,run,now,db}=require('../db'); const {id}=require('../utils/ids'); const {num,bool}=require('../utils/env'); const wallet=require('./walletService'); const director=require('./videoDirectorService'); const bibleService=require('./visualBibleService'); const anchors=require('./memoryAnchorService'); const snapshots=require('./projectMemorySnapshotService'); const billing=require('./billingService');
function shotCount(duration){ return Math.ceil(Number(duration||num('DEFAULT_SHORT_VIDEO_DURATION_SECONDS',30))/num('DEFAULT_SHOT_DURATION_SECONDS',5)); }
function durationLimit(user){ if(user.plan==='factory') return num('MAX_FACTORY_PROJECT_DURATION_SECONDS',600); if(user.plan==='studio') return num('MAX_STUDIO_PROJECT_DURATION_SECONDS',300); if(user.plan==='creator') return num('MAX_CREATOR_PROJECT_DURATION_SECONDS',120); const w=wallet.ensureWallet(user.id); return w.paid_balance>0?num('MAX_PAID_PROJECT_DURATION_SECONDS',60):num('MAX_FREE_PROJECT_DURATION_SECONDS',0); }
function estimateCredits(projectType,duration,level){ if(['copy','marketing','script'].includes(projectType)) return .08; const shots=shotCount(duration); const base=projectType==='video'||projectType==='product_ad'||projectType==='business_promo'?3:0.15; return Math.round(shots*base*(director.levels[level]||1)*100)/100; }
async function createProject(user,input){ const target=Number(input.target_duration_seconds||num('DEFAULT_SHORT_VIDEO_DURATION_SECONDS',30)); if(['video','product_ad','business_promo'].includes(input.project_type||'video') && target>durationLimit(user)) throw new Error('duration_requires_upgrade'); const level=input.director_supervision_level||'off'; if(level!=='off') director.assertLevel(user.plan,level); const count=shotCount(target); const est=estimateCredits(input.project_type||'video',target,level); const available=wallet.hasAvailable(user.id,est,{paidOnly:false}); const pid=input.continuation_mode==='resume_same_project'&&input.parent_project_id?input.parent_project_id:id('prj'); const series=input.continuation_mode==='sequel'&&input.parent_project_id?(get('SELECT series_id FROM projects WHERE id=?',[input.parent_project_id])?.series_id||id('series')):id('series'); const status=available.ok?'pending':'waiting_for_balance'; return db.transaction(()=>{ run('INSERT OR IGNORE INTO projects (id,user_id,title,series_id,root_project_id,parent_project_id,project_no,project_type,continuation_mode,memory_mode,inherited_snapshot_id,memory_namespace,created_from_project_id,target_platform,aspect_ratio,target_duration_seconds,target_length,script_text,visual_style,director_supervision_level,status,estimated_credits,provider,real_api,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[pid,user.id,input.title||'Untitled LingMirror Project',series,pid,input.parent_project_id||null,1,input.project_type||'video',input.continuation_mode||'new_project',input.memory_mode||'clean',input.inherited_snapshot_id||null,`${series}:${pid}`,input.created_from_project_id||null,input.target_platform||'short_video',input.aspect_ratio||'9:16',target,input.target_length||'custom',input.script_text||'',input.visual_style||'premium cinematic',level,status,est,'volcengine',bool('ENABLE_REAL_API')?1:0,now(),now()]); for(let i=1;i<=count;i++){ const sid=id('shot'); run('INSERT INTO shots (id,project_id,shot_no,duration,prompt,negative_prompt,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)',[sid,pid,i,num('DEFAULT_SHOT_DURATION_SECONDS',5),`Shot ${i}: ${(input.script_text||'Create a consistent LingMirror AI video').slice(0,260)}`,'avoid face drift, black bars, crop, prop changes','pending',now(),now()]); if(i===1) run('UPDATE projects SET next_pending_shot_id=? WHERE id=?',[sid,pid]); }
 run('INSERT INTO project_events (id,project_id,user_id,event_type,description,metadata_json,created_at) VALUES (?,?,?,?,?,?,?)',[id('pe'),pid,user.id,'project_created',`Estimated ${est} credits, ${count} shots`,JSON.stringify({available}),now()]); return get('SELECT * FROM projects WHERE id=?',[pid]); })(); }
async function planProject(projectId){ const p=get('SELECT * FROM projects WHERE id=?',[projectId]); if(!p) throw new Error('project_not_found'); run('UPDATE projects SET status=?,updated_at=? WHERE id=?',['planning',now(),projectId]); const bible=await bibleService.createVisualBible(p); await anchors.createInitialAnchors(projectId,bible.data); const snap=await snapshots.saveSnapshot(projectId,'auto_checkpoint',{nextShotId:p.next_pending_shot_id}); run('UPDATE projects SET status=?,provider=?,model=?,fallback_used=?,latest_memory_snapshot_id=?,updated_at=? WHERE id=?',['pending',bible.provider,bible.model,bible.fallback_used?1:0,snap.id,now(),projectId]); return get('SELECT * FROM projects WHERE id=?',[projectId]); }
function listProjects(userId){ return all('SELECT * FROM projects WHERE user_id=? ORDER BY created_at DESC',[userId]); }
function detail(projectId){ return {project:get('SELECT * FROM projects WHERE id=?',[projectId]),shots:all('SELECT * FROM shots WHERE project_id=? ORDER BY shot_no',[projectId]),anchors:all('SELECT * FROM memory_anchors WHERE project_id=? ORDER BY created_at DESC',[projectId]),frames:all('SELECT * FROM memory_frames WHERE project_id=? ORDER BY created_at DESC',[projectId]),snapshots:all('SELECT * FROM project_memory_snapshots WHERE project_id=? ORDER BY snapshot_no DESC',[projectId]),history:all('SELECT * FROM shot_generation_history WHERE project_id=? ORDER BY created_at DESC',[projectId]),usage:all('SELECT * FROM api_usage_logs WHERE project_id=? ORDER BY created_at DESC',[projectId])}; }
function autoResumePausedProjects(userId){ const projects=all("SELECT * FROM projects WHERE user_id=? AND status='paused_insufficient_balance'",[userId]); const resumed=[]; for(const p of projects){ const need=Math.min(3,p.estimated_credits-p.spent_credits||3); const check=wallet.hasAvailable(userId,need,{paidOnly:p.project_type==='video'}); if(check.ok){ run('UPDATE projects SET status=?,updated_at=? WHERE id=?',['pending',now(),p.id]); run("UPDATE generation_jobs SET status='pending',updated_at=? WHERE project_id=? AND status='paused_insufficient_balance'",[now(),p.id]); resumed.push(p.id); } }
 return resumed; }
module.exports={createProject,planProject,listProjects,detail,autoResumePausedProjects,shotCount,estimateCredits};
