const cloud = require('wx-server-sdk');
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
const db = cloud.database();
const _ = db.command;
const BLOCK = ['约炮','裸聊','赌博','博彩','诈骗','血腥'];
const RISK = ['自杀','轻生','不想活','割腕','跳楼','伤害自己'];
function moderate(text){ const content=String(text||'').trim(); const b=BLOCK.find(w=>content.includes(w)); if(b) return {status:'blocked',reason:`命中禁止内容：${b}`,visible:false}; const r=RISK.find(w=>content.includes(w)); if(r) return {status:'review',reason:'疑似自伤/轻生表达，将进入人工审核并降低扩散。',care:true,visible:false}; return content?{status:'safe',reason:'通过模拟审核',visible:true}:{status:'blocked',reason:'内容不能为空',visible:false}; }
function parse(text, emotionTag='', theme=''){ const has=(w)=>String(text).includes(w); const emotion=emotionTag || (has('雨')?'孤独':has('爱')||has('你')?'恋爱':has('冲')||has('跑')?'热血':has('猫')||has('哈哈')?'搞笑':'治愈'); const colors=emotion.includes('孤独')?['#1B1D2A','#596175']:emotion.includes('恋爱')?['#FFE5EC','#FFD1DC']:emotion.includes('热血')?['#FFE0C2','#FF6B4A']:['#F6F3EE','#DDE7F0']; const elements=[]; function add(id,type,x,y){ if(!elements.find(e=>e.id===id)) elements.push({id,type,position:{x,y},style:{strokeWidth:type==='line_person'?3:2,opacity:.85}}); } add('person_1','line_person',160,330); if(has('风')) add('wind_1','wind_line',0,190); if(has('雨')) add('rain_1','rain',40,80); if(has('心')||has('你')) add('heart_1','heart_line',220,230); if(has('碎')||has('破防')) add('broken_heart_1','broken_heart',220,230); if(has('海')) add('wave_1','wave',180,380); if(has('云')) add('cloud_1','cloud',80,120); if(has('猫')) add('cat_1','cat',230,320); const timeline=[{time:0,target:'text',action:'glow',duration:.6,sound:'soft_start'},{time:.55,target:'text',action:'text_to_line',duration:.8,sound:'line_draw'}]; elements.forEach((e,i)=>timeline.push({time:1+i*.45,target:e.id,action:e.type==='wind_line'?'move_left_to_right':e.type==='rain'?'rain_fall_to_stop':e.type==='heart_line'?'heartbeat_once':e.type==='broken_heart'?'crack':e.type==='wave'?'wave_push':e.type==='cat'?'cat_jump_in':'idle_waiting',duration:3.5,sound:e.type==='wind_line'?'wind_soft':e.type==='rain'?'rain_soft':e.type.includes('heart')?'heartbeat_soft':e.type==='wave'?'ocean_soft':e.type==='cat'?'cat_meow_soft':null})); timeline.push({time:5.5,target:'all',action:'fade_out',duration:.5}); return {emotion,scene:theme||'留白文案空间',sound:[...new Set(timeline.map(t=>t.sound).filter(Boolean))],preview_config:{layout:String(text).length>28?'poem_lines':'hero_sentence',fontSize:String(text).length>28?34:48,highlight:text,emotion,scene:theme,background:{type:'gradient',colors},accentColor:colors[1],elements:elements.map(e=>e.type),hint:'长按让文字活过来'},animation_manifest:{post_id:'',text,duration:6,theme:emotion,background:{type:'gradient',colors},elements,timeline}}; }
module.exports={cloud,db,_,moderate,parse};
