const express=require('../utils/miniExpress'); const {requireAdmin}=require('../utils/security'); const {all,get,run,now}=require('../db'); const wallet=require('../services/walletService'); const project=require('../services/projectService'); const r=express.Router();
r.use(requireAdmin);
r.get('/summary',(req,res)=>{ const today=new Date().toISOString().slice(0,10); res.json({users:get('SELECT COUNT(*) count FROM users'),projects:get('SELECT COUNT(*) count FROM projects'),wallets:all('SELECT * FROM wallets ORDER BY updated_at DESC LIMIT 50'),today_income:get("SELECT COALESCE(SUM(user_charge),0) total FROM api_usage_logs WHERE created_at LIKE ?",[`${today}%`]),today_cost:get("SELECT COALESCE(SUM(actual_cost),0) total FROM api_usage_logs WHERE created_at LIKE ?",[`${today}%`]),today_profit:get("SELECT COALESCE(SUM(profit),0) total FROM api_usage_logs WHERE created_at LIKE ?",[`${today}%`])}); });
for (const t of ['users','wallets','wallet_transactions','recharge_orders','subscriptions','payment_logs','webhook_events','projects','shots','generation_jobs','project_memory_snapshots','memory_anchors','memory_frames','visual_entities','api_usage_logs','provider_cost_logs','profit_logs','business_jobs']) r.get(`/${t}`,(req,res)=>res.json(all(`SELECT * FROM ${t} ORDER BY created_at DESC LIMIT 200`)));
r.post('/wallets/:userId/credit',(req,res)=>{ const tx=wallet.credit(req.params.userId,Number(req.body.amount||0),req.body.description||'Admin compensation',{bucket:req.body.bucket||'paid'}); res.json({tx,resumed:project.autoResumePausedProjects(req.params.userId)}); });
r.post('/projects/:id/pause',(req,res)=>{ run('UPDATE projects SET status=?,updated_at=? WHERE id=?',['manual_review',now(),req.params.id]); res.json({ok:true}); });
r.post('/projects/:id/resume',(req,res)=>{ run('UPDATE projects SET status=?,updated_at=? WHERE id=?',['pending',now(),req.params.id]); res.json({ok:true}); });
r.post('/projects/:id/deliver',(req,res)=>{ run('UPDATE projects SET status=?,updated_at=? WHERE id=?',['delivered',now(),req.params.id]); res.json({ok:true}); });
module.exports=r;
