const express=require('../utils/miniExpress'); const {requireAuth}=require('../utils/security'); const ah=require('../utils/asyncHandler'); const {run,get,all,now}=require('../db'); const {id}=require('../utils/ids'); const wallet=require('../services/walletService'); const billing=require('../services/billingService'); const budget=require('../services/apiBudgetService'); const providerBalance=require('../services/providerBalanceService'); const volc=require('../providers/volcengineProvider'); const mock=require('../services/mockProvider'); const usage=require('../services/usageLogService'); const {route}=require('../services/modelRouter'); const r=express.Router();
async function textJob(req,res,module,taskType,promptBuilder,minCharge=.05){ const userId=req.user.sub; const input=req.body; const estimated=billing.calculateUserCharge(taskType,billing.estimateProviderCost(taskType,{tokens:1800})); const bj=id('biz'); run('INSERT INTO business_jobs (id,user_id,module,input_json,status,estimated_charge,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)',[bj,userId,module,JSON.stringify(input),'running',estimated,now(),now()]); let result; try{ budget.assertWithinPlatformBudget(.02); providerBalance.assertCanCall(taskType); result=await billing.guardedCall({userId,jobId:bj,taskType,estimatedCharge:estimated,providerCall:()=>volc.callTextModel({model:route(taskType),taskType,messages:[{role:'user',content:promptBuilder(input)}]})}); }catch(e){ result={...mock[taskType]?.(input)||mock.copy_generation(input),fallback_used:true,error_message:e.message,user_charge:0}; }
 run('UPDATE business_jobs SET output_json=?,status=?,actual_charge=?,updated_at=? WHERE id=?',[JSON.stringify(result),result.status||'succeeded',result.user_charge||0,now(),bj]); run('INSERT INTO copy_jobs (id,user_id,business_job_id,task_type,input_json,output_text,model,provider,status,estimated_charge,actual_charge,fallback_used,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[id('copy'),userId,bj,taskType,JSON.stringify(input),result.output_text,result.model,result.provider,result.status,estimated,result.user_charge||0,result.fallback_used?1:0,now()]); usage.recordUsage({userId,jobId:bj,provider:result.provider,model:result.model,taskType,usage:result.usage,estimatedCost:result.estimated_provider_cost||0,actualCost:result.actual_provider_cost||0,userCharge:result.user_charge||0,status:result.status,errorMessage:result.error_message||''}); res.json({job_id:bj,result,wallet:wallet.ensureWallet(userId)}); }
r.post('/copy-lab',requireAuth,ah((req,res)=>textJob(req,res,'copy_lab','copy_generation',i=>`Generate TikTok Hook, YouTube Shorts Script, Instagram Caption, Facebook Ad Copy, Google Ad Copy, SEO title/description, landing page copy, email marketing and video storyboard for: ${JSON.stringify(i)}`)));
r.post('/product-ads',requireAuth,ah((req,res)=>textJob(req,res,'product_ads','product_ad_generation',i=>`Generate e-commerce selling points, ad copy and short video storyboard for product: ${JSON.stringify(i)}`)));
r.post('/business-promo',requireAuth,ah((req,res)=>textJob(req,res,'business_promo','business_promo_generation',i=>`Create company promo script, bilingual outline and shot plan: ${JSON.stringify(i)}`)));
r.post('/ecommerce',requireAuth,ah((req,res)=>textJob(req,res,'ecommerce','ecommerce_material_generation',i=>`Create e-commerce main image copy, detail page copy and English ad localization: ${JSON.stringify(i)}`)));
r.post('/knowledge-base',requireAuth,ah((req,res)=>textJob(req,res,'knowledge_base','knowledge_base_answer',i=>`Answer from supplied FAQ/product information. If missing, say what source is needed. ${JSON.stringify(i)}`)));
r.post('/image-poster',requireAuth,ah((req,res)=>textJob(req,res,'image_poster','poster_generation',i=>`Create poster prompt, layout and headline for: ${JSON.stringify(i)}`)));
r.post('/three-d-asset',requireAuth,ah((req,res)=>textJob(req,res,'three_d_asset','three_d_asset_prompt_generation',i=>`Create text-to-3D and image-to-3D prompts for: ${JSON.stringify(i)}`)));
r.get('/history',requireAuth,(req,res)=>res.json(all('SELECT * FROM business_jobs WHERE user_id=? ORDER BY created_at DESC LIMIT 100',[req.user.sub])));
module.exports=r;
