require('./env');
const http = require('http'), fs = require('fs'), path = require('path'), crypto = require('crypto');
const { run, get, all } = require('./db');
const { aiGenerate } = require('./aiProvider');
const PORT = process.env.PORT || 3001, HOST = process.env.HOST || '127.0.0.1';
const JWT_SECRET = process.env.JWT_SECRET || 'dev-change-me', CONTACT_EMAIL = process.env.CONTACT_EMAIL || 'zhishiliu057@gmail.com';
const pub = path.join(__dirname, '..', 'public');
const send=(res,code,obj,type='application/json')=>{res.writeHead(code,{'Content-Type':type});res.end(type==='application/json'?JSON.stringify(obj):obj)};
const readBody=req=>new Promise(ok=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch{ok({})}})});
const b64=o=>Buffer.from(typeof o==='string'?o:JSON.stringify(o)).toString('base64url');
const sign=data=>crypto.createHmac('sha256',JWT_SECRET).update(data).digest('base64url');
function tokenFor(u){const h=b64({alg:'HS256',typ:'JWT'}), p=b64({id:u.id,email:u.email,exp:Math.floor(Date.now()/1000)+604800}); return `${h}.${p}.${sign(`${h}.${p}`)}`}
function verify(t){const [h,p,s]=String(t||'').split('.'); if(!h||!p||s!==sign(`${h}.${p}`)) throw Error('bad'); const o=JSON.parse(Buffer.from(p,'base64url')); if(o.exp<Date.now()/1000) throw Error('exp'); return o;}
const hashPass=p=>{const salt=crypto.randomBytes(16).toString('hex'); const h=crypto.pbkdf2Sync(p,salt,100000,32,'sha256').toString('hex'); return `pbkdf2$${salt}$${h}`};
const checkPass=(p,stored)=>{const [,salt,h]=String(stored||'').split('$'); if(!salt) return false; return crypto.timingSafeEqual(Buffer.from(h),Buffer.from(crypto.pbkdf2Sync(p,salt,100000,32,'sha256').toString('hex')))};
const publicUser=u=>u&&({id:u.id,email:u.email,display_name:u.display_name,created_at:u.created_at});
async function ensureWallet(userId){let w=await get('SELECT * FROM wallets WHERE user_id=?',[userId]); if(!w){await run('INSERT INTO wallets (user_id) VALUES (?)',[userId]); w=await get('SELECT * FROM wallets WHERE user_id=?',[userId]);} return w;}
function authed(req){const h=req.headers.authorization||''; if(!h.startsWith('Bearer ')) throw Error('login_required'); return verify(h.slice(7));}
function isAdmin(req){return process.env.ADMIN_PASSWORD && req.headers['x-admin-password']===process.env.ADMIN_PASSWORD}
async function audit(action,details){await run('INSERT INTO admin_audit_logs (action,details) VALUES (?,?)',[action,JSON.stringify(details||{})])}
async function resumePaused(userId){const r=await run("UPDATE projects SET status='pending',updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND status='paused_insufficient_balance'",[userId]); return r.changes||0}
async function creditPaid(userId,amount,description='PayPal manual top-up'){await ensureWallet(userId); await run('UPDATE wallets SET paid_balance=paid_balance+?,current_balance=paid_balance+?+bonus_balance,updated_at=CURRENT_TIMESTAMP WHERE user_id=?',[amount,amount,userId]); await run('INSERT INTO wallet_transactions (user_id,type,bucket,amount,description,provider) VALUES (?,?,?,?,?,?)',[userId,'credit','paid',amount,description||'PayPal manual top-up','paypal_manual']); return resumePaused(userId)}
async function route(req,res){const url=new URL(req.url,`http://${req.headers.host}`), p=url.pathname, method=req.method; try{
 if(p==='/health') return send(res,200,'OK','text/plain');
 if(!p.startsWith('/api/')){let file=path.normalize(path.join(pub,p==='/'?'/index.html':p)); if(!file.startsWith(pub)||!fs.existsSync(file)||fs.statSync(file).isDirectory()) file=path.join(pub,'index.html'); const ext=path.extname(file); return send(res,200,fs.readFileSync(file), ext==='.css'?'text/css':ext==='.js'?'application/javascript':'text/html');}
 if(p==='/api/config') return send(res,200,{version:'LingMirror AI v1.0 LTS 商用冻结版',contact_email:CONTACT_EMAIL,paypal:{recharge_10:process.env.PAYPAL_RECHARGE_10_LINK,recharge_30:process.env.PAYPAL_RECHARGE_30_LINK,recharge_100:process.env.PAYPAL_RECHARGE_100_LINK,recharge_300:process.env.PAYPAL_RECHARGE_300_LINK,sub_creator:process.env.PAYPAL_SUB_CREATOR_PLAN_ID,sub_studio:process.env.PAYPAL_SUB_STUDIO_PLAN_ID,sub_factory:process.env.PAYPAL_SUB_FACTORY_PLAN_ID},video_enabled:process.env.VOLCENGINE_ENABLE_VIDEO==='true'});
 if(p==='/api/auth/register'&&method==='POST'){const b=await readBody(req), email=String(b.email||'').toLowerCase().trim(), password=String(b.password||''); if(!email||password.length<6) return send(res,400,{error:'valid_email_and_6_char_password_required'}); try{const r=await run('INSERT INTO users (email,password_hash,display_name) VALUES (?,?,?)',[email,hashPass(password),email.split('@')[0]]); const u=await get('SELECT * FROM users WHERE id=?',[r.lastID]); await ensureWallet(u.id); return send(res,200,{token:tokenFor(u),user:publicUser(u)})}catch(e){return send(res,409,{error:'email_exists_or_invalid'})}}
 if(p==='/api/auth/login'&&method==='POST'){const b=await readBody(req), email=String(b.email||'').toLowerCase().trim(); const u=await get('SELECT * FROM users WHERE email=?',[email]); if(!u||!u.password_hash||!checkPass(String(b.password||''),u.password_hash)) return send(res,401,{error:'invalid_email_or_password'}); await ensureWallet(u.id); return send(res,200,{token:tokenFor(u),user:publicUser(u)})}
 if(p==='/api/auth/google/start'){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET) return send(res,503,{error:'google_oauth_not_configured',message:'Google login is being configured, please use email login first.'}); const cb=encodeURIComponent(process.env.GOOGLE_CALLBACK_URL), state=crypto.randomBytes(12).toString('hex'); return send(res,200,{url:`https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(process.env.GOOGLE_CLIENT_ID)}&redirect_uri=${cb}&response_type=code&scope=${encodeURIComponent('openid email profile')}&state=${state}`})}
 if(p==='/api/auth/google/callback'){try{if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET) throw Error('google_oauth_not_configured'); const params=new URLSearchParams({code:url.searchParams.get('code')||'',client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_CALLBACK_URL,grant_type:'authorization_code'}); const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params}); if(!tr.ok) throw Error('google_token_failed'); const tj=await tr.json(); const ur=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${tj.access_token}`}}); if(!ur.ok) throw Error('google_userinfo_failed'); const g=await ur.json(); if(!g.email) throw Error('google_email_missing'); let u=await get('SELECT * FROM users WHERE email=?',[g.email.toLowerCase()]); if(!u){const r=await run('INSERT INTO users (email,google_sub,display_name) VALUES (?,?,?)',[g.email.toLowerCase(),g.sub,g.name||g.email]); u=await get('SELECT * FROM users WHERE id=?',[r.lastID]);} await ensureWallet(u.id); res.writeHead(302,{Location:`/dashboard.html?token=${encodeURIComponent(tokenFor(u))}`}); return res.end()}catch(e){res.writeHead(302,{Location:`/login.html?google_error=${encodeURIComponent(e.message)}`}); return res.end()}}
 let user; if(!p.startsWith('/api/admin/')) user=authed(req);
 if(p==='/api/me') return send(res,200,{user:publicUser(await get('SELECT * FROM users WHERE id=?',[user.id]))});
 if(p==='/api/wallet') return send(res,200,{wallet:await ensureWallet(user.id),transactions:await all('SELECT * FROM wallet_transactions WHERE user_id=? ORDER BY id DESC LIMIT 50',[user.id])});
 let m=p.match(/^\/api\/ai\/([^/]+)$/); if(m&&method==='POST'){const b=await readBody(req), module=m[1], map={'copy-lab':'cheap','product-ads':'strong','business-promo':'strong','ecommerce-studio':'default','knowledge-base':'default','image-poster':'strong','styles':'default','memory-anchor':'vision','business-center':'default'}; const out=await aiGenerate({userId:user.id,module,task:map[module]||'default',prompt:JSON.stringify(b)}); if(module==='memory-anchor') await run('INSERT INTO memory_anchors (user_id,title,content,provider,model) VALUES (?,?,?,?,?)',[user.id,b.title||'Memory Anchor',out.text,out.provider,out.model]); return send(res,200,{result:out.text,...out})}
 if(p==='/api/projects'&&method==='POST'){const b=await readBody(req), title=String(b.title||'Untitled Project').slice(0,120), duration=Number(b.duration_seconds||60), estimated=Number((Math.max(1,duration/30)*2).toFixed(2)), w=await ensureWallet(user.id); const status=w.current_balance<estimated?'paused_insufficient_balance':'pending', videoEnabled=process.env.VOLCENGINE_ENABLE_VIDEO==='true'; const r=await run('INSERT INTO projects (user_id,title,type,status,estimated_cost,paid_required) VALUES (?,?,?,?,?,?)',[user.id,title,'video',status,estimated,videoEnabled?1:0]); const out=await aiGenerate({userId:user.id,projectId:r.lastID,module:'project',task:'strong',prompt:`Create video package for ${title}. ${JSON.stringify(b)}`}); const result={script:out.text,shot_plan:['Hook','Product proof','Offer','CTA'],visual_bible:'Consistent brand colors and commercial continuity.',memory_anchor:'Project tone and continuity stored.',mock_preview_frame:'/storage/frames/mock-preview.png',video_notice:videoEnabled?'Real video enabled only after paid-balance and budget checks.':'Video API not enabled yet. Current version generates scripts, shot plans, memory and mock preview only.',provider:out.provider,fallback_used:out.fallback_used,real_api:out.real_api}; await run('UPDATE projects SET result_json=? WHERE id=?',[JSON.stringify(result),r.lastID]); await run('INSERT INTO project_memory_snapshots (project_id,user_id,snapshot_json) VALUES (?,?,?)',[r.lastID,user.id,JSON.stringify(result)]); await run('INSERT INTO generation_jobs (project_id,user_id,module,status,provider,model,fallback_used,result_json) VALUES (?,?,?,?,?,?,?,?)',[r.lastID,user.id,'AI Video Factory',status==='pending'?'pending':'paused',out.provider,out.model,out.fallback_used?1:0,JSON.stringify(result)]); return send(res,200,{project:{id:r.lastID,title,status,estimated_cost:estimated,result},...out})}
 if(p==='/api/projects'&&method==='GET') return send(res,200,{projects:await all('SELECT id,title,type,status,estimated_cost,created_at,updated_at FROM projects WHERE user_id=? ORDER BY id DESC',[user.id])});
 m=p.match(/^\/api\/projects\/(\d+)$/); if(m&&method==='GET'){const pr=await get('SELECT * FROM projects WHERE id=? AND user_id=?',[m[1],user.id]); if(!pr) return send(res,404,{error:'project_not_found'}); pr.result=pr.result_json?JSON.parse(pr.result_json):null; delete pr.result_json; return send(res,200,{project:pr})}
 if(p.startsWith('/api/admin/')){if(!isAdmin(req)) return send(res,401,{error:process.env.ADMIN_PASSWORD?'admin_login_required':'admin_password_not_configured'});
  if(p==='/api/admin/summary') {const u=await get('SELECT COUNT(*) c FROM users'), pr=await get('SELECT COUNT(*) c FROM projects'), money=await get("SELECT COALESCE(SUM(CASE WHEN type='credit' THEN amount ELSE 0 END),0) revenue FROM wallet_transactions WHERE date(created_at)=date('now')"), cost=await get("SELECT COALESCE(SUM(actual_cost),0) cost, COALESCE(SUM(profit),0) profit FROM api_usage_logs WHERE date(created_at)=date('now')"); return send(res,200,{users:u.c,projects:pr.c,today_income:money.revenue,today_cost:cost.cost,today_profit:cost.profit})}
  if(p==='/api/admin/users') return send(res,200,{users:await all('SELECT u.id,u.email,u.display_name,u.created_at,w.current_balance,w.paid_balance,w.bonus_balance,w.frozen_balance,w.spent_total FROM users u LEFT JOIN wallets w ON w.user_id=u.id WHERE u.email LIKE ? ORDER BY u.id DESC LIMIT 100',[`%${url.searchParams.get('email')||''}%`])});
  m=p.match(/^\/api\/admin\/users\/(\d+)\/credit$/); if(m&&method==='POST'){const b=await readBody(req), amount=Number(b.amount); if(!(amount>0)) return send(res,400,{error:'positive_amount_required'}); const resumed=await creditPaid(m[1],amount,b.description||'PayPal manual top-up'); await audit('credit_paid_balance',{userId:m[1],amount,provider:'paypal_manual',resumed}); return send(res,200,{ok:true,resumed_projects:resumed,transaction:{type:'credit',bucket:'paid',description:b.description||'PayPal manual top-up',provider:'paypal_manual'}})}
  if(p==='/api/admin/projects'){const st=url.searchParams.get('status'); return send(res,200,{projects:await all(st?'SELECT p.*,u.email FROM projects p JOIN users u ON u.id=p.user_id WHERE p.status=? ORDER BY p.id DESC LIMIT 100':'SELECT p.*,u.email FROM projects p JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 100',st?[st]:[])})}
  m=p.match(/^\/api\/admin\/projects\/(\d+)\/resume$/); if(m&&method==='POST'){await run("UPDATE projects SET status='pending',updated_at=CURRENT_TIMESTAMP WHERE id=?",[m[1]]); await audit('resume_project',{projectId:m[1]}); return send(res,200,{ok:true,status:'pending'})}
  if(p==='/api/admin/ops') return send(res,200,{api_usage_logs:await all('SELECT * FROM api_usage_logs ORDER BY id DESC LIMIT 100'),project_memory_snapshots:await all('SELECT * FROM project_memory_snapshots ORDER BY id DESC LIMIT 50'),memory_anchors:await all('SELECT * FROM memory_anchors ORDER BY id DESC LIMIT 50'),generation_jobs:await all('SELECT * FROM generation_jobs ORDER BY id DESC LIMIT 50'),wallet_transactions:await all('SELECT * FROM wallet_transactions ORDER BY id DESC LIMIT 100')});
 }
 return send(res,404,{error:'not_found'});
}catch(e){ if(e.message==='login_required'||e.message==='bad'||e.message==='exp') return send(res,401,{error:'login_required'}); console.error(e.message); return send(res,500,{error:'server_error',message:e.message}); }}
http.createServer(route).listen(PORT,HOST,()=>console.log(`LingMirror AI v1.0 LTS 商用冻结版 listening on http://${HOST}:${PORT}`));
