"""initial schema with pgvector memory anchors
Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-05
"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("title", sa.String(200), nullable=False), sa.Column("type", sa.String(50), nullable=False), sa.Column("duration_seconds", sa.Integer(), nullable=False), sa.Column("aspect_ratio", sa.String(20), nullable=False), sa.Column("visual_style", sa.String(80), nullable=False), sa.Column("director_personality", sa.String(80), nullable=False), sa.Column("target_audience", sa.String(200), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("story_bibles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), unique=True), sa.Column("world_view", sa.Text(), nullable=False), sa.Column("core_hook", sa.Text(), nullable=False), sa.Column("tone", sa.Text(), nullable=False), sa.Column("emotion_curve", sa.Text(), nullable=False), sa.Column("director_notes", sa.Text(), nullable=False), sa.Column("visual_rules", sa.Text(), nullable=False), sa.Column("negative_rules", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("scripts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), unique=True), sa.Column("synopsis", sa.Text(), nullable=False), sa.Column("three_act_structure", sa.JSON(), nullable=False), sa.Column("scene_script", sa.JSON(), nullable=False), sa.Column("dialogue", sa.JSON(), nullable=False), sa.Column("shot_outline", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("characters", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("role_type", sa.String(80), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("personality", sa.Text(), nullable=False), sa.Column("appearance", sa.Text(), nullable=False), sa.Column("costume", sa.Text(), nullable=False), sa.Column("voice_profile", sa.Text(), nullable=False), sa.Column("reference_front_path", sa.String(500)), sa.Column("reference_side_path", sa.String(500)), sa.Column("reference_full_body_path", sa.String(500)), sa.Column("expression_sheet_path", sa.String(500)), sa.Column("is_selected", sa.Boolean(), nullable=False), sa.Column("is_locked", sa.Boolean(), nullable=False), sa.Column("score", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("assets", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("asset_type", sa.String(80), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("reference_image_path", sa.String(500)), sa.Column("is_locked", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("shots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("shot_number", sa.Integer(), nullable=False), sa.Column("duration_seconds", sa.Integer(), nullable=False), sa.Column("story_goal", sa.Text(), nullable=False), sa.Column("characters_json", sa.JSON(), nullable=False), sa.Column("location_id", sa.Integer()), sa.Column("props_json", sa.JSON(), nullable=False), sa.Column("camera_instruction", sa.Text(), nullable=False), sa.Column("action_instruction", sa.Text(), nullable=False), sa.Column("lighting_instruction", sa.Text(), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("video_path", sa.String(500)), sa.Column("first_frame_path", sa.String(500)), sa.Column("last_frame_path", sa.String(500)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("shot_prompts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("shot_id", sa.Integer(), sa.ForeignKey("shots.id")), sa.Column("prompt_text", sa.Text(), nullable=False), sa.Column("negative_prompt", sa.Text(), nullable=False), sa.Column("memory_context", sa.Text(), nullable=False), sa.Column("first_frame_path", sa.String(500)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("generation_tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("shot_id", sa.Integer(), sa.ForeignKey("shots.id")), sa.Column("provider_name", sa.String(80), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("request_payload", sa.JSON(), nullable=False), sa.Column("response_payload", sa.JSON(), nullable=False), sa.Column("error_message", sa.Text()), sa.Column("retry_count", sa.Integer(), nullable=False), sa.Column("output_video_path", sa.String(500)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("memory_anchors", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("shot_id", sa.Integer(), sa.ForeignKey("shots.id")), sa.Column("memory_type", sa.String(80), nullable=False), sa.Column("entities_json", sa.JSON(), nullable=False), sa.Column("scene_description", sa.Text(), nullable=False), sa.Column("continuity_notes", sa.Text(), nullable=False), sa.Column("style_lock", sa.Text(), nullable=False), sa.Column("first_frame_path", sa.String(500)), sa.Column("last_frame_path", sa.String(500)), sa.Column("keyframes_json", sa.JSON(), nullable=False), sa.Column("embedding_vector", Vector(1536), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("continuity_reports", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("shot_id", sa.Integer(), sa.ForeignKey("shots.id")), sa.Column("character_score", sa.Float(), nullable=False), sa.Column("background_score", sa.Float(), nullable=False), sa.Column("costume_score", sa.Float(), nullable=False), sa.Column("prop_score", sa.Float(), nullable=False), sa.Column("color_score", sa.Float(), nullable=False), sa.Column("transition_score", sa.Float(), nullable=False), sa.Column("total_score", sa.Float(), nullable=False), sa.Column("passed", sa.Boolean(), nullable=False), sa.Column("failure_reasons", sa.Text(), nullable=False), sa.Column("repair_suggestions", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("exports", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id")), sa.Column("final_video_path", sa.String(500)), sa.Column("subtitle_path", sa.String(500)), sa.Column("audio_path", sa.String(500)), sa.Column("status", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))

def downgrade() -> None:
    for t in ["exports","continuity_reports","memory_anchors","generation_tasks","shot_prompts","shots","assets","characters","scripts","story_bibles","projects"]:
        op.drop_table(t)
