const http=require('http'), fs=require('fs'), path=require('path'), url=require('url');
function compile(p){ const keys=[]; const re='^'+p.replace(/\//g,'/').replace(/:([^/]+)/g,(_,k)=>{keys.push(k);return'([^/]+)'})+'/?$'; return {re:new RegExp(re),keys}; }
function enhance(res){ res.statusCode=200; res.status=function(c){this.statusCode=c;return this}; res.json=function(o){this.setHeader('Content-Type','application/json');this.end(JSON.stringify(o))}; res.send=function(x){ if(typeof x==='object') return this.json(x); this.end(String(x)); }; res.type=function(t){this.setHeader('Content-Type',t);return this}; res.redirect=function(loc){this.statusCode=302;this.setHeader('Location',loc);this.end()}; return res; }
function app(){ const routes=[],mws=[]; const handle=(req,res)=>{ enhance(res); const parsed=url.parse(req.url,true); req.path=parsed.pathname; req.query=parsed.query; req.params={}; let i=0; const stack=[...mws, dispatch]; function next(err){ if(err) return error(err,req,res); const fn=stack[i++]; if(fn) { if(fn.length===4) return next(); fn(req,res,next); } } function dispatch(req,res,next){ for(const r of routes){ const m=r.comp.re.exec(req.path); if(r.method===req.method&&m){ r.comp.keys.forEach((k,i)=>req.params[k]=decodeURIComponent(m[i+1])); return r.fn(req,res,next); } } if(req.path==='/'||req.path==='/index.html') return sendFile(res,path.join(process.cwd(),'public/index.html')); res.status(404).json({error:'not_found'}); } next(); };
 handle.use=(prefix,fn)=>{ if(typeof prefix==='function'){mws.push(prefix);return} if(fn&&fn._routes){ for(const r of fn._routes) { const full=(prefix+(r.path==='/'?'':r.path))||'/'; routes.push({...r,path:full,comp:compile(full)}); }; } else if(typeof fn==='function') mws.push((req,res,next)=> req.path.startsWith(prefix)?fn(req,res,next):next()); };
 ['get','post'].forEach(method=>handle[method]=(p,...fns)=>routes.push({method:method.toUpperCase(),path:p,comp:compile(p),fn:chain(fns)})); handle.listen=(port,host,cb)=>http.createServer(handle).listen(port,host,cb); return handle; }
function chain(fns){ return (req,res,next)=>{ let i=0; const run=(err)=>{ if(err) return next(err); const fn=fns[i++]; if(!fn) return next(); try{ fn(req,res,run); }catch(e){next(e)} }; run(); }; }
function Router(){ const r={_routes:[],_middlewares:[]}; ['get','post'].forEach(method=>r[method]=(p,...fns)=>r._routes.push({method:method.toUpperCase(),path:p,comp:compile(p),fn:chain([...r._middlewares,...fns])})); r.use=(fn)=>{ if(typeof fn==='function') r._middlewares.push(fn); }; return r; }
function json(){ return (req,res,next)=>{ if(!['POST','PUT','PATCH'].includes(req.method)) return next(); let b=''; req.on('data',c=>b+=c); req.on('end',()=>{ try{req.body=b?JSON.parse(b):{}}catch{req.body={}}; next(); }); }; }
function urlencoded(){ return (req,res,next)=>next(); }
function sendFile(res,file){ fs.readFile(file,(e,d)=>{ if(e) return res.status(404).end('not found'); const ext=path.extname(file); const map={'.html':'text/html','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml','.mp4':'video/mp4'}; res.setHeader('Content-Type',map[ext]||'application/octet-stream'); res.end(d); }); }
function stat(root){ return (req,res,next)=>{ const clean=req.path.replace(/^\/storage/,'').replace(/^\//,''); const file=path.join(root, decodeURIComponent(clean)); if(file.startsWith(root)&&fs.existsSync(file)&&fs.statSync(file).isFile()) return sendFile(res,file); next(); }; }
function error(err,req,res){ console.error(err); if(!res.status) enhance(res); res.status(err.message&&err.message.includes('insufficient')?402:500).json({error:err.message||'server_error'}); }
app.Router=Router; app.json=json; app.urlencoded=urlencoded; app.static=stat; module.exports=app;
