const fs=require('fs'); const path=require('path'); const {str,bool,num}=require('../utils/env'); const billing=require('../services/billingService'); const {id}=require('../utils/ids');
async function fetchJson(url,options){ const res=await fetch(url,options); const text=await res.text(); let json={}; try{json=JSON.parse(text)}catch{json={raw:text}} if(!res.ok) throw Object.assign(new Error(json.error?.message||text||res.statusText),{status:res.status,json}); return json; }
function enabled(kind){ return bool('ENABLE_REAL_API') && bool(`VOLCENGINE_ENABLE_${kind.toUpperCase()}`) && !!str('VOLCENGINE_ARK_API_KEY'); }
function unified(p){ return {provider:'volcengine',model:p.model,task_type:p.task_type,status:p.status||'succeeded',provider_task_id:p.provider_task_id||'',request_payload:p.request_payload||{},response_payload:p.response_payload||{},output_text:p.output_text||'',output_url:p.output_url||'',usage:p.usage||{},estimated_provider_cost:p.estimated_provider_cost||0,actual_provider_cost:p.actual_provider_cost||0,user_charge:p.user_charge||0,error_code:p.error_code||'',error_message:p.error_message||''}; }
async function callTextModel({model,messages,taskType='copy_generation',temperature=0.7}){ if(!enabled('TEXT')) throw new Error('volcengine_text_not_configured'); const payload={model,messages,temperature}; const json=await fetchJson(`${str('VOLCENGINE_ARK_BASE_URL')}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${str('VOLCENGINE_ARK_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}); const out=json.choices?.[0]?.message?.content||''; const usage={input_tokens:json.usage?.prompt_tokens||0,output_tokens:json.usage?.completion_tokens||0,total_tokens:json.usage?.total_tokens||0}; const cost=estimateProviderCost(taskType,{tokens:usage.total_tokens||1200}); return unified({model,task_type:taskType,request_payload:{model,temperature},response_payload:{id:json.id},output_text:out,usage,estimated_provider_cost:cost,actual_provider_cost:cost,user_charge:calculateUserCharge(taskType,cost)}); }
async function callVisionModel({model,frameUrl,context={}}){ if(!enabled('VISION')) throw new Error('volcengine_vision_not_configured'); const messages=[{role:'user',content:[{type:'text',text:`Analyze this frame for LingMirror Memory Anchor JSON: ${JSON.stringify(context)}`},{type:'image_url',image_url:{url:frameUrl}}]}]; return callTextModel({model,messages,taskType:'memory_anchor',temperature:0.2}); }
async function callEmbeddingModel({model,text}){ if(!enabled('EMBEDDING')) throw new Error('volcengine_embedding_not_configured'); const json=await fetchJson(`${str('VOLCENGINE_ARK_BASE_URL')}/embeddings`,{method:'POST',headers:{Authorization:`Bearer ${str('VOLCENGINE_ARK_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:text})}); const vector=json.data?.[0]?.embedding||[]; const cost=estimateProviderCost('embedding',{tokens:Math.ceil(text.length/4)}); return unified({model,task_type:'embedding',response_payload:{id:json.id},output_text:JSON.stringify(vector),usage:json.usage||{},estimated_provider_cost:cost,actual_provider_cost:cost,user_charge:calculateUserCharge('short_copy',cost)}); }
async function createImageTask({model,prompt}){ return unified({model,task_type:'image_generation',status:'succeeded',provider_task_id:id('imgtask'),output_url:'/assets/samples/mock-poster.svg',estimated_provider_cost:.18,actual_provider_cost:.18,user_charge:billing.calculateUserCharge('image_generation',.18)}); }
function validateSeedancePayload(payload){ const ratios=['21:9','16:9','4:3','1:1','3:4','9:16','adaptive']; if(payload.duration<num('MIN_SHOT_DURATION_SECONDS',4)||payload.duration>num('MAX_SHOT_DURATION_SECONDS',15)) throw new Error('invalid_seedance_duration'); if(!ratios.includes(payload.ratio)) throw new Error('invalid_seedance_ratio'); const fast=payload.model===str('VIDEO_MODEL_FAST'); const allowed=fast?['480p','720p']:['480p','720p','1080p']; if(!allowed.includes(payload.resolution)) throw new Error('invalid_seedance_resolution'); if(payload.format!=='mp4') throw new Error('invalid_seedance_format'); return true; }
function buildSeedancePayload({prompt,duration=5,ratio='16:9',resolution='720p',quality='fast',content=[]}){ const model=quality==='quality'?str('VIDEO_MODEL_QUALITY'):str('VIDEO_MODEL_FAST'); const numbered=content.map((c,i)=>({...c,label:`${c.type==='video'?'视频':c.type==='audio'?'音频':'图片'}${i+1}`})); const payload={model,prompt,duration,ratio,resolution,format:'mp4',content:numbered}; validateSeedancePayload(payload); return payload; }
async function createVideoTask(payload){ if(!enabled('VIDEO')) throw new Error('volcengine_video_not_enabled'); validateSeedancePayload(payload); const json=await fetchJson(`${str('VOLCENGINE_ARK_BASE_URL')}/contents/generations/tasks`,{method:'POST',headers:{Authorization:`Bearer ${str('VOLCENGINE_ARK_API_KEY')}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}); return unified({model:payload.model,task_type:'video_generation',status:'running',provider_task_id:json.id||json.task_id,request_payload:{...payload,prompt:payload.prompt},response_payload:json,estimated_provider_cost:estimateProviderCost('video_generation',{duration:payload.duration}),user_charge:calculateUserCharge('video_generation',estimateProviderCost('video_generation',{duration:payload.duration}))}); }
async function getVideoTask(taskId){ if(!enabled('VIDEO')) throw new Error('volcengine_video_not_enabled'); const json=await fetchJson(`${str('VOLCENGINE_ARK_BASE_URL')}/contents/generations/tasks/${taskId}`,{headers:{Authorization:`Bearer ${str('VOLCENGINE_ARK_API_KEY')}`}}); return normalizeTaskStatus(json); }
async function pollVideoTask(taskId,{maxPolls=20,intervalMs=30000}={}){ for(let i=0;i<maxPolls;i++){ const r=await getVideoTask(taskId); if(['succeeded','failed'].includes(r.status)) return r; await new Promise(res=>setTimeout(res,intervalMs)); } throw new Error('video_poll_timeout'); }
function normalizeTaskStatus(json){ const statusMap={success:'succeeded',succeeded:'succeeded',failed:'failed',running:'running',queued:'running'}; const raw=json.status||json.task_status; return unified({model:json.model||'',task_type:'video_generation',status:statusMap[raw]||'running',provider_task_id:json.id||json.task_id,output_url:json.output?.video_url||json.video_url||'',response_payload:json,actual_provider_cost:json.cost||0}); }
async function downloadAndPersistVideo(url,projectId,shotId){ const out=`/storage/videos/${projectId}_${shotId}.mp4`; const full=path.join(process.cwd(),out); if(url && url.startsWith('http')){ const res=await fetch(url); fs.writeFileSync(full, Buffer.from(await res.arrayBuffer())); } else fs.writeFileSync(full,'mock video placeholder'); return out; }
function estimateProviderCost(taskType,opts){ return billing.estimateProviderCost(taskType,opts); } function calculateUserCharge(taskType,cost,opts){ return billing.calculateUserCharge(taskType,cost,opts); }
module.exports={callTextModel,callVisionModel,callEmbeddingModel,createImageTask,createVideoTask,getVideoTask,pollVideoTask,downloadAndPersistVideo,normalizeTaskStatus,estimateProviderCost,calculateUserCharge,buildSeedancePayload,validateSeedancePayload};
